name: Testes Automatizados

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout do codigo
      uses: actions/checkout@v2
    - name: Definir PythonPath
      run: |
        $env:PYTHONPATH += ";" + $env:GITHUB_WORKSPACE + "\Codificacao"
    - name: Verificar PYTHONPATH
      run: echo $env:PYTHONPATH
      
    - name: Listar conteúdo do diretório
      run: |
        dir $env:GITHUB_WORKSPACE\Codificacao
        
    - name: Ambiente
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    
  
        
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r Codificacao/requirements.txt

    - name: Execucao de testes
      run: |
        coverage run -m pytest
    
